name: NPM Publish

# This action will trigger on every release get created.
on: push
#  release:
#    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: pnpm run build
      # Publish the files to NPM.
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish --access public
      # For publishing, NPM needs authorization. We add the NPM token to the environment which will take care of authorization to publish to the package.
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_KEY}}
